name: colav_unsafe_set_gen CI/CD
run-name: ${{ github.actor }} is testing colav_unsafe_set_gen pypi pkg 🚀

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]
  release: 
    types: [created]

jobs: 
  test: 
    name: Run Tests
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.10"

      - name: Install build tools
        run: pip install build twine setuptools

      - name: Build unsafe_set_gen pkg
        run: python -m build

      - name: Publish pkg to PyPI
        if: github.event_name == 'push'
        env: 
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/* -u "__token__" -p "pypi-AgEIcHlwaS5vcmcCJDFkY2QyMDUyLTA1OTQtNDczZi04ODFmLTZjNjJhY2I0NWI0MAACKlszLCIyNjExYjI2YS0xMGJhLTQ1OGMtYTFkMC00ZWQ0YWE5YWM1ZGYiXQAABiDUQAT2yc_zQC78--U7CYreEgn_f0cFubDi-UN3MeWm4Q" --non-interactive